#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"

		delete system.ntp.server
		add_list system.ntp.server="ntp.tencent.com"
		add_list system.ntp.server="ntp1.aliyun.com"
		add_list system.ntp.server="ntp.ntsc.ac.cn"
		add_list system.ntp.server="cn.ntp.org.cn"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.pku.edu.cn/immortalwrt"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi
sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"


uci_dns="$(uci -q get luci.diag.dns)"
uci_ping="$(uci -q get luci.diag.ping)"
uci_route="$(uci -q get luci.diag.route)"

default_diag_domin="immortalwrt.org"
if [ -z "$uci_dns" ] || [ -z "$uci_ping" ] || [ -z "$uci_route" ]; then
    if [[  "$uci_dns" == "$default_diag_domin" ]] && [[ "$uci_ping" == "$default_diag_domin" ]] && [[ "$uci_route" == "$default_diag_domin" ]]; then
		uci -q batch <<-EOF
            set luci.diag.dns="www.baidu.com"
            set luci.diag.ping="www.baidu.com"
            set luci.diag.route="www.baidu.com"
            commit luci
		EOF
		sed -i.bak "s,immortalwrt.org,$default_diag_domin,g" "/etc/config/luci.conf"
    fi
fi

exit 0